# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

source: ./
destination: _site
sass:
  sass_dir: _sass
  style: expanded # compressed # expanded

# permalink and highlighter
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

# SEO settings
title: Critical Care Data London - Datathon 2016
description: "We invite clinicians and data scientists, experts and novices to come and explore two iconic clinical data repositories with talks from experts in electronic health records, 'big data' and database design."
keywords: "healthcare, medicine, data, science, research, audit, quality, R, python, excel, doctor, nurse"

# Site settings
url: http://datascicc.org/
baseurl: ""

# Author settings
author:
  name      : Critical Care Data London
  email     : hello@datascicc.org
  url       : http://datascicc.org/
  twitter   : https://twitter.com/criticaldatauk

# google_analytics: UA-52446115-1
# repo: http://github.com/nandomoreirame/dotX

# comments
disqus_shortname: "CCD-Datathon-2016"
